name: Test Flaky

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Check version
        run: git checkout 3a7c35a014f8a3471a1b75e7546e01ecf21d5db3

      - name: Compile the project
        run: mvn test-compile -pl core -am
  
      - name: Run tests
        run: mvn -pl core test -Dtest=org.apache.struts2.views.freemarker.FreemarkerResultMockedTest#testDynamicAttributesSupport
        
      # - name: Set up JDK 8 for NonDex
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '8'
  
      - name: Run NonDex to check for flaky tests
        run: mvn -pl core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.struts2.views.freemarker.FreemarkerResultMockedTest#testDynamicAttributesSupport -DnondexRuns=10
